title: Random bits and pieces
description: > # this means to ignore newlines until "baseurl:"
    ...about programming, languages, tools, OS software.... by Igor Dejanović.

author:
  name: Igor Dejanović
  email: igor.dejanovic@gmail.com

baseurl: "/"
url: "http://igordejanovic.net"
twitter: dejanovicigor
github:  igordejanovic
disqus-shortname: igordejanovic

date_format: "%Y-%m-%d"

# Build settings
paginate: 5
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
