title: Random bits and pieces
description: > # this means to ignore newlines until "baseurl:"
    ...about programming, languages, tools, FLOSS software.... by Igor Dejanović.

author:
  name: Igor Dejanović
  email: igor.dejanovic@gmail.com

baseurl: ""
url: "http://www.igordejanovic.net"
twitter: dejanovicigor
github:  igordejanovic
disqus-shortname: igordejanovic

date_format: "%Y-%m-%d"

# Github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# Build settings
paginate: 5
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - courses/base_slides.md
  - courses/tech/*.md
  - courses/jsd/*.md
  - courses/uks/*.md
  - courses/sok/*.md
  - courses/ntp/*.md
