name: Random bits and pieces
description: ...mostly about software development
meta_description: "Blog about technology by Igor Dejanović"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'igordejanovic.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://igordejanovic.github.io'
author:         'Igor Dejanović'
