baseURL = "https://www.igordejanovic.net"
title = "Random bits and pieces"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

# ignoreFiles = ['\.org$']

[params.info]
description = "...about programming, languages, tools, and FOSS software by Igor Dejanović"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
#customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Igor Dejanović"
startYear = "2016"
suffix = "-- Created with [Org Mode](https://orgmode.org/), [ox-hugo](https://ox-hugo.scripter.co/), [Hugo](https://gohugo.io/) with [minimo theme](https://github.com/MunifTanjim/minimo)."

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
#header = ["breadcrumbs"]
#homepage = ["recent_posts"]
sidebar = ["about", "social_menu", "sidebar_menu", "search"] #,"taxonomy_cloud"]
#footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = ""
email = "igor.dejanovic@gmail.com"
#facebook = ""
github = "igordejanovic"
gitlab = "igordejanovic"
#instagram = ""
linkedin = "igor-dejanović-62bb921"
twitter = "dejanovicigor"
#telegram = ""
google_scholar = "SqLKTIkAAAAJ"
youtube = "UC-Sge0qopo1q3U7RzLtGLyA"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = ""
repository = ""

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[taxonomies]
ptag = "ptags"  # post tags
rtag = "rtags"  # recipe tags
# tag = "tags"  # recipe tags

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[widgets.taxonomy_cloud]
#title = ""                # default: Plural Name for `taxonomyCloud.taxonomy`
#taxonomy = "tags"         # default: "tags"
shuffle = false           # default: true

[params.widgets.breadcrumbs]
separator = "/"                      # default: "/"
excludeParents = ["page"]

# [menu]
#   [[menu.main]]
#     identifier = "home"
#     name = "Home"
#     url = "/"
#     weight = 1
#   [[menu.main]]
#     identifier = "courses"
#     name = "Courses"
#     url = "/courses/"
#     weight = 2
#   [[menu.main]]
#     identifier = "projects"
#     name = "Projects"
#     url = "/projects/"
#     weight = 3
#   [[menu.main]]
#     identifier = "interviews"
#     name = "Interviews"
#     url = "/interviews/"
#     weight = 4
#   [[menu.main]]
#     identifier = "mentoring"
#     name = "Mentoring"
#     url = "/mentoring/"
#     weight = 5
#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/about/"
#     weight = 10
