@startuml
  class Projekat {
          naziv: string
          git_repo: string
  }
  Projekat *-- "0..*" Problem
  class Problem {
          naslov: string
  }
  Problem "*" -- "*" Problem
  class Komentar {
          opis: string
  }
  Problem *-- "1..*" Događaj
  Događaj "*" -- Korisnik

  class Događaj {
          vreme: timestamp
  }
  class PromenaStanja {
          novo_stanje: StanjeProblema
  }
  class PromenaOdgovornog {
          odgovoran: Korisnik
  }
  class PromenaKontrolneTačke {
  }
  class PromenaKoda{
          url: URL
  }
  Događaj <|-- PromenaStanja
  Događaj <|-- Komentar
  Događaj <|-- PromenaKomentara
  Događaj <|-- PromenaOdgovornog
  Događaj <|-- PromenaKontrolneTačke
  Događaj <|-- PromenaKoda

  class KontrolnaTačka {
          datum: date
  }
  Projekat *--> "*" KontrolnaTačka
  PromenaKontrolneTačke --> "0..1" KontrolnaTačka

  enum StanjeProblema {
          Otvoren,
          Zatvoren
  }

  class Labela {
          naziv: string
          boja: string
  }

  Problem -- "0..*" Labela

  class Korisnik {
          ime: string
          email: EMail
  }
@enduml
